Repository Ivan907/ForMCsalkov, pull requests merged in 2024-12, with the labels that each got.

#6 Добавлено техническое задание
  README.md
  Техническое задание.md
Labels: documentation

#7 Минимальный шаблон и инструкция
  README.md
  index.html
  script.js
  style.css
  Инструкция по развертыванию.md
Labels: documentation, enhancement

#9 Создание интерфейса игры
  index.html
  script.js
  style.css
Labels: enhancement

#10 Добавление препятствий и столкновений
  index.html
  script.js
  style.css
Labels: enhancement
